#! /bin/bash

source ./deploy-config

npm run build

ssh -p $SPOKTOR_SSH_PORT $SPOKTOR_SSH_USER@$SPOKTOR_SSH_HOST \
    "rm -rf $SPOKTOR_REMOTE_DEPLOY_PATH && \
    mkdir -p $SPOKTOR_REMOTE_DEPLOY_PATH"

scp -r -P $SPOKTOR_SSH_PORT ./build/* $SPOKTOR_SSH_USER@$SPOKTOR_SSH_HOST:$SPOKTOR_REMOTE_DEPLOY_PATH
