#! /bin/bash

source ./.env

ssh -p $SPOKTOR_SSH_PORT $SPOKTOR_SSH_USER@$SPOKTOR_SSH_HOST \
    "rm -rf $SPOKTOR_REMOTE_DEPLOY_PATH && \
    mkdir -p $SPOKTOR_REMOTE_DEPLOY_PATH"

scp -r -P $SPOKTOR_SSH_PORT ./src/* $SPOKTOR_SSH_USER@$SPOKTOR_SSH_HOST:$SPOKTOR_REMOTE_DEPLOY_PATH

ssh -p $SPOKTOR_SSH_PORT $SPOKTOR_SSH_USER@$SPOKTOR_SSH_HOST \
    ln -s $SPOKTOR_REMOTE_DEPLOY_PATH/domain $SPOKTOR_REMOTE_DEPLOY_PATH/delivery/web/domain
